name: FireWings
main: FireWings\Main
version: 1.3
api: [1.1.3, 2.0.0, 2.0.1, 3.0.0, 3.0.1, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15]
author: "vk.com/eddir"
translator: GamerSoiCon
commands:
  wing:
    description: Nhận lấy cánh !
    permission: firewings.command.wing
    usage: /wing
permissions:
  firewings.command.wing:
    default: true
    description: Cho phép người chơi sử dụng lệnh /wing !
